#!/usr/bin/env bash
set -eo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

git submodule update --init --recursive

./dotbot/bin/dotbot \
    --base-directory "$(pwd)" \
    --config-file "install.conf.yaml" \
    "${@}"
