call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Older versions of vim don't behave with fish shell
if !has("patch-7.4.276") && $SHELL =~ 'bin/fish'
 set shell=/bin/sh
endif

set nocompatible
set number
set ruler

filetype on
filetype plugin on
syntax enable

" Searching
set ignorecase smartcase
set incsearch
set hlsearch
nnoremap <ESC><ESC> :nohlsearch<cr>

" ctrlp fuzzy file search
let g:ctrlp_cache_dir = $HOME . '/.cache/ctrlp'
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif
let g:ctrlp_match_window = 'results:100'

" No swap files
set noswapfile
set nobackup
set nowb
set autoread "reload files changed outside of vim

" Indentation
set smarttab
set autoindent
set softtabstop=4
set shiftwidth=4
set tabstop=4
set expandtab

set showcmd
set backspace=indent,eol,start

" disable arrow keys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

noremap <space>= :Tabularize /=<cr>
set colorcolumn=101

" Use tab to navigate splits.
nnoremap <tab> <C-w><C-w>
nnoremap <s-tab> <C-w><left>

" Color scheme
syntax enable
set background=dark
colorscheme molokai
let g:solarized_bold=0
highlight ColorColumn ctermbg=8

" Show whitespace (default off for now, too distracting)
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
"set list

" Plugins and stuff
set wildignore+=*.o,*.obj,.git,node_modules

" Syntastic is so slow sometimes :(
let g:syntastic_mode_map = { 'mode': 'passive', 'active_filetypes': [],'passive_filetypes': [] }


" UltiSnips is pretty darn lovely
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
